year: 2022
lumi: 7.980
lumiunit: fb
genweight: "1."
treename: Events
analysisname: Trota_TopSF_2022
processes:
  data:
    nominal_files:
      - /eos/user/l/lfavilla/RDF_DManalysis/TopSF/ntuples_ready_for_TopSF_Framework/DataJetMETC_2022/DataJetMETC_2022_nominal.root
  qcd:
    nominal_files:
      - /eos/user/l/lfavilla/RDF_DManalysis/TopSF/ntuples_ready_for_TopSF_Framework/QCD_HT1500to2000_2022/QCD_HT1500to2000_2022_nominal.root
    unc_files:
      JES:
        up:
          - /eos/user/l/lfavilla/RDF_DManalysis/TopSF/ntuples_ready_for_TopSF_Framework/QCD_HT1500to2000_2022/QCD_HT1500to2000_2022_jesUp.root
        down:
          - /eos/user/l/lfavilla/RDF_DManalysis/TopSF/ntuples_ready_for_TopSF_Framework/QCD_HT1500to2000_2022/QCD_HT1500to2000_2022_jesDown.root
      JER:
        up:
          - /eos/user/l/lfavilla/RDF_DManalysis/TopSF/ntuples_ready_for_TopSF_Framework/QCD_HT1500to2000_2022/QCD_HT1500to2000_2022_jerUp.root
        down:
          - /eos/user/l/lfavilla/RDF_DManalysis/TopSF/ntuples_ready_for_TopSF_Framework/QCD_HT1500to2000_2022/QCD_HT1500to2000_2022_jerDown.root
  ttbar:
    nominal_files:
      - /eos/user/l/lfavilla/RDF_DManalysis/TopSF/ntuples_ready_for_TopSF_Framework/TT_semilep_2022/TT_semilep_2022_nominal.root
    unc_files:
      JES:
        up:
          - /eos/user/l/lfavilla/RDF_DManalysis/TopSF/ntuples_ready_for_TopSF_Framework/TT_semilep_2022/TT_semilep_2022_jesUp.root
        down:
          - /eos/user/l/lfavilla/RDF_DManalysis/TopSF/ntuples_ready_for_TopSF_Framework/TT_semilep_2022/TT_semilep_2022_jesDown.root
      JER:
        up:
          - /eos/user/l/lfavilla/RDF_DManalysis/TopSF/ntuples_ready_for_TopSF_Framework/TT_semilep_2022/TT_semilep_2022_jerUp.root
        down:
          - /eos/user/l/lfavilla/RDF_DManalysis/TopSF/ntuples_ready_for_TopSF_Framework/TT_semilep_2022/TT_semilep_2022_jerDown.root
basecut: "1."
categories:
  topmatched:
    processes:
      - ttbar
    cut: "TopMixedMatched_to_GenTop_dR0p2"
  nonmatched:
    processes:
      - ttbar
    cut: "!(TopMixedMatched_to_GenTop_dR0p2)"
  other:
    processes:
      - qcd
    cut: "1"
tagger:
  name: BestTopMixed_TightWP
  varname: BestTopMixed_score
  cut: 0.7214655876159668
distribution:
  variables:
    - variable: BestTopMixed_mass
      range: [0, 1000]
      bins: 20
  event_categories:
    - name: pt300to400
      rule: "(BestTopMixed_pt>=300) && (BestTopMixed_pt<400)"
uncertainties:
  lumi:
    mode: "lnN"
    size: 1.025
  pu:
    mode: "factor"
    up: "puWeightUp/puWeight"
    down: "puWeightDown/puWeight"
  JES:
    mode: "file"
  JER:
    mode: "file"